// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwimStats.Data;

#nullable disable

namespace SwimStats.Data.Migrations
{
    [DbContext(typeof(SwimStatsDbContext))]
    partial class SwimStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SwimStats.Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stroke")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Stroke", "DistanceMeters", "Course");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SwimStats.Core.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwimmerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EventId");

                    b.HasIndex("SwimmerId", "EventId", "Date", "Course");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("SwimStats.Core.Models.Swimmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Swimmers");
                });

            modelBuilder.Entity("SwimStats.Core.Models.Result", b =>
                {
                    b.HasOne("SwimStats.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwimStats.Core.Models.Swimmer", "Swimmer")
                        .WithMany()
                        .HasForeignKey("SwimmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Swimmer");
                });
#pragma warning restore 612, 618
        }
    }
}
